refactor: use decimal as min_base_fee
skip-mev/feemarket pull request #66
Opened 2024-03-29 13:05 UTC by MSalopek

This PR changes the feemarket implementation to use a decimal instead of an int for the `min_base_fee` field.

Not using a decimal could cause an inadvertant and unexpeced rise in the gas fee costs.

In some calculations I was not sure about the correctnes of the operation. Search for `// Note: not sure about` across the repo.

Feedback is appreciated.

2024-03-29 13:36 UTC, aljo242 requested changes

2024-03-29 13:36 UTC, aljo242 commented on README.md
> +    (cosmos_proto.scalar) = "cosmos.Legacy",
```suggestion
    (cosmos_proto.scalar) = "cosmos.Dec",
```

2024-03-29 13:36 UTC, aljo242 commented on proto/feemarket/feemarket/v1/genesis.proto
> +    (cosmos_proto.scalar) = "cosmos.Legacy",
```suggestion
    (cosmos_proto.scalar) = "cosmos.Dec",
```

2024-03-29 13:51 UTC, MSalopek commented on README.md
> +    (cosmos_proto.scalar) = "cosmos.Legacy",
Updated

2024-03-29 13:51 UTC, MSalopek commented on proto/feemarket/feemarket/v1/genesis.proto
> +    (cosmos_proto.scalar) = "cosmos.Legacy",
Updated

2024-04-01 18:24 UTC, aljo242 commented
@MSalopek I'm not so sure that moving to use a decimal value is going to be a good idea here.  Or at least this implementation of it.

In the event where the decimal value goes below 1, anytime the [TruncateInt](https://github.com/cosmos/cosmos-sdk/blob/80e1a45e706bb0db46813fdcc33f78eda66554a9/math/dec.go#L720) is called, the value is rounded _down_, meaning the resulting fee will be 0 right?

I don't thing there should ever be a case where the on-chain fee is 0.  Is this behavior you are intending?

2024-04-01 18:26 UTC, aljo242 commented
There should at least be logic that ensures that the resulting fee is non-zero

2024-04-02 19:39 UTC, aljo242 requested changes

2024-04-02 19:39 UTC, aljo242 commented on x/feemarket/post/fee.go
> +	// Note: not sure about the TruncateInt() method call
remove

2024-04-02 19:46 UTC, MSalopek commented on x/feemarket/post/fee.go
> +	// Note: not sure about the TruncateInt() method call
removed

2024-04-05 18:32 UTC, aljo242 approved these changes
Approving - but there are some caveats here:

This code must be tested much further before it is brought into production.  I would recommend expanding on the `tests/e2e` directory we have significantly before bringing to prod. Load tests as well

2024-04-08 14:46 UTC, merged